export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILIURE = "FETCH_PRODUCTS_FAILURE";



export const FETCH_CATEGORY_PRODUCTS_REQUEST = "FETCH_CATEGORY_PRODUCTS_REQUEST";
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = "FETCH_CATEGORY_PRODUCTS_SUCCESS";
export const FETCH_CATEGORY_PRODUCTS_FAILURE = "FETCH_CATEGORY_PRODUCTS_FAILURE";


export const FETCH_QUANTITY_PRODUCTS_REQUEST = "FETCH_QUANTITY_PRODUCTS_REQUEST";
export const FETCH_QUANTITY_PRODUCTS_SUCCESS = "FETCH_QUANTITY_PRODUCTS_SUCCESS";
export const FETCH_QUANTITY_PRODUCTS_FAILURE = "FETCH_QUANTITY_PRODUCTS_FAILURE";